# åŸºæœ¬è¨­å®š
baseurl = "https://minnanosaiban.github.io/medical-fraud/"
title = "åŸå‘Šå‹è¨´ï¼ã€€å…¬ç›Šé€šå ±è€…ã«å¯¾ã™ã‚‹å ±å¾©æªç½®ãŒèªã‚ã‚‰ã‚Œã¾ã—ãŸã€‚ä¸æ­£è¨ºç™‚è«‹æ±‚ã€æ£æ„çš„ãªåŒ»ç™‚ã€å›½æ°‘ãŒåã‚ãŸç¨é‡‘ãƒ»ç¤¾ä¼šä¿é™ºæ–™ã®ç„¡é§„é£ã„ã¯è¨±ã•ãªã„ğŸ“Œ" # â˜…â˜…â˜…æ¤œç´¢ã‚¨ãƒ³ã‚¸ãƒ³å‘ã‘ã®ã‚¿ã‚¤ãƒˆãƒ«
languageCode = "ja-JP"
pagination.pagerSize = "10"
theme = "mainroad"
# ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«
# [Author]
#   name = "TOMO"
#   bio = "éã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã§ã™"
#   avatar = "img/avatar.png"
[Params]
  description = "åŸå‘Šå‹è¨´ï¼ã€€å…¬ç›Šé€šå ±è€…ã«å¯¾ã™ã‚‹å ±å¾©æªç½®ãŒèªã‚ã‚‰ã‚Œã¾ã—ãŸã€‚ä¸æ­£è¨ºç™‚è«‹æ±‚ã€æ£æ„çš„ãªåŒ»ç™‚ã€å›½æ°‘ãŒåã‚ãŸç¨é‡‘ãƒ»ç¤¾ä¼šä¿é™ºæ–™ã®ç„¡é§„é£ã„ã¯è¨±ã•ãªã„ğŸ“Œ" # â˜…â˜…â˜… æ¤œç´¢ã‚¨ãƒ³ã‚¸ãƒ³å‘ã‘ã®èª¬æ˜
  copyright = "TOMO" # è‘—ä½œæ¨©è¡¨ç¤º
  opengraph = true # Twitter ã«å¼µã‚Šä»˜ã‘ãŸéš›ã«ãƒ—ãƒ¬ãƒ“ãƒ¥ãƒ¼ã‚’æœ‰åŠ¹åŒ–
  schema = true # SEOå‘ã‘æ§‹é€ åŒ–ãƒ‡ãƒ¼ã‚¿ã‚’æœ‰åŠ¹åŒ–
  twitter_cards = true # Twitterã‚«ãƒ¼ãƒ‰ã‚’æœ‰åŠ¹åŒ–
  readmore = true # ã€Œç¶šãã‚’èª­ã‚€ã€ãƒœã‚¿ãƒ³ã®æœ‰åŠ¹åŒ–
  authorbox = false # è‘—è€…æƒ…å ±ã®è¡¨ç¤ºã‚’æœ‰åŠ¹åŒ–
  toc = false # ç›®æ¬¡ï¼ˆTable of Contentsï¼‰ã‚’æœ‰åŠ¹åŒ–
  pager = false # å‰å¾Œã®è¨˜äº‹ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã‚’æœ‰åŠ¹åŒ–
  post_meta =  ["author", "date", "categories", "translations"] # è¨˜äº‹ã«è¡¨ç¤ºã™ã‚‹ãƒ¡ã‚¿æƒ…å ±ã®é †åº
  mainSections = [] # ãƒˆãƒƒãƒ—ãƒšãƒ¼ã‚¸ã«è¡¨ç¤ºã™ã‚‹ã‚»ã‚¯ã‚·ãƒ§ãƒ³
  dateformat = "2006-01-02" # æ—¥ä»˜ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆï¼ˆYYYY-MM-DDï¼‰
  # mathjax = false # æ•°å¼è¡¨ç¤ºã‚’æœ‰åŠ¹åŒ–
  # mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # 
  # mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # 
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&display=swap" # ãƒ•ã‚©ãƒ³ãƒˆã‚’ã‚«ã‚¹ã‚¿ãƒã‚¤ã‚º
  customCSS = ["css/custom.css"] # ã‚«ã‚¹ã‚¿ãƒ CSSã‚’é©ç”¨
  customJS = ["js/custom.js"] # ã‚«ã‚¹ã‚¿ãƒ JSã‚’é©ç”¨
[Params.style.vars]
  highlightColor = "#4A90E2"  # â˜…â˜…â˜… ã‚µã‚¤ãƒˆã®ã‚¢ã‚¯ã‚»ãƒ³ãƒˆã‚«ãƒ©ãƒ¼
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif" # åŸºæœ¬ã®ãƒ•ã‚©ãƒ³ãƒˆ
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace" # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ç”¨ã®ãƒ•ã‚©ãƒ³ãƒˆ
[Params.logo]
  # image = "img/logo.png" # â˜…â˜…â˜… ãƒ­ã‚´
  title = "åŒ»ç™‚ç¾å ´ã€ãƒ›ãƒ³ãƒˆã®ç¾å®Ÿ"
  subtitle = "åŸå‘Šå‹è¨´ï¼ã€€å…¬ç›Šé€šå ±è€…ã«å¯¾ã™ã‚‹å ±å¾©æªç½®ãŒèªã‚ã‚‰ã‚Œã¾ã—ãŸã€‚å›½æ°‘ãŒåã‚ãŸç¨é‡‘ãƒ»ç¤¾ä¼šä¿é™ºæ–™ã®ç„¡é§„é£ã„ã¯è¨±ã•ãªã„ğŸ“Œ"
# [Params.thumbnail]
  # visibility = ["list", "post"] # ã‚µãƒ ãƒã‚¤ãƒ«ç”»åƒã®è¨­å®š
[Params.sidebar]
  home = "left" # ãƒˆãƒƒãƒ—ãƒšãƒ¼ã‚¸ã®ã‚µã‚¤ãƒ‰ãƒãƒ¼ä½ç½®
  list = "left"  # è¨˜äº‹ãƒªã‚¹ãƒˆã®ã‚µã‚¤ãƒ‰ãƒãƒ¼ä½ç½®
  single = true # å€‹åˆ¥è¨˜äº‹ãƒšãƒ¼ã‚¸ã«ã‚µã‚¤ãƒ‰ãƒãƒ¼ã‚’è¡¨ç¤ºã™ã‚‹ã‹
  widgets = ["sitemap", "taglist"]  #  ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã®é †åº ["categories", "taglist", "githubpages", "mhlw", "nttdata", "eneos",]
[Params.widgets]
  # recent_num = 5 # ã€Œæœ€è¿‘ã®æŠ•ç¨¿ã€ã®è¨˜äº‹æ•°
  categories_counter = true # ã‚«ãƒ†ã‚´ãƒªã®æŠ•ç¨¿æ•°ã®æœ‰åŠ¹åŒ–
  tags_counter = true # ã‚¿ã‚°ã®æŠ•ç¨¿æ•°ã®æœ‰åŠ¹åŒ–
# [Params.widgets.githubpages]
  # custom = [
    # { title = "ï¼¥ï¼®ï¼¥ï¼¯ï¼³ã®å†…éƒ¨é€šå ±åˆ¶åº¦ã«é–¢ã™ã‚‹è¨´è¨Ÿã«ã¤ã„ã¦", url = "https://minnanosaiban.github.io/hotline/" },
    # { title = "Another Page", url = "https://example.com" }
  # ]
[Params.widgets.social] # SNSã‚¢ã‚¤ã‚³ãƒ³ã®æœ‰åŠ¹åŒ–
  cached = false # ã‚­ãƒ£ãƒƒã‚·ãƒ¥ã‚’ç„¡åŠ¹åŒ–ï¼ˆtrue ã«ã™ã‚‹ã¨é«˜é€ŸåŒ–ã§ãã‚‹ï¼‰
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  # github = "username"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
